const VERSION='v03';
const K_STATE='inventory_state_'+VERSION,K_WH='inventory_warehouse_'+VERSION,K_POS='inventory_position_'+VERSION,K_CUSTOM='inventory_custom_'+VERSION;
const $=id=>document.getElementById(id);const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let stock=JSON.parse(localStorage.getItem(K_CUSTOM)||'null')||window.STOCK_DATA;let state=JSON.parse(localStorage.getItem(K_STATE)||'{}');let warehouse=localStorage.getItem(K_WH)||'PFC Bar';let position=JSON.parse(localStorage.getItem(K_POS)||'{}');
const PFC_LOCS=[
 {id:'sklep',name:'Jeskyně / sklep',desc:'Sudy s pivem',enabled:false},
 {id:'sklad',name:'Sklad',desc:'Basy s pivem a nealkem',enabled:true},
 {id:'regal',name:'Regál',desc:'Tvrdý alkohol a víno',enabled:true},
 {id:'lednice',name:'Nealko lednice',desc:'Chlazené nealko, pivo a načaté víno',enabled:true},
 {id:'vinoteka',name:'Vinotéka',desc:'Lahvová vína',enabled:true},
 {id:'box',name:'Chladicí box',desc:'Bedny prosecca, nealko vína, PET a občas pivo',enabled:true}
];
const DECKO_LOCS=[{id:'bar',name:'Bar / sklad Déčko',desc:'Dočasné pořadí podle kategorií',enabled:true}];
function isKeg(x){return /\bkeg\b|sud/i.test(x.name)}function isReturnable(x){return x.category==='Obaly'||/vratn|kelimek|pet lahev 2/i.test(norm(x.name))}
function pfcLocations(x){if(isKeg(x))return ['sklep'];if(isReturnable(x))return [];
 const n=norm(x.name),c=x.category;
 if(c==='Spirit')return ['regal'];
 if(c==='Víno'){
   if(/prosecco|nealko|sparkling|dc /.test(n))return ['regal','lednice','vinoteka','box'];
   if(/fangalo|bib/.test(n))return ['regal','lednice'];
   return ['regal','lednice','vinoteka'];
 }
 if(c==='Pivo'||c==='Pivo Permon')return ['sklad','lednice','box'];
 if(c==='Nealko'){
   if(/sirup|bib/.test(n))return ['sklad'];
   if(/pet|kofola|coca|sprite|voda/.test(n))return ['sklad','lednice','box'];
   return ['sklad','lednice'];
 }
 if(c==='Káva'||c==='Koloniál')return ['sklad'];
 if(c==='Nanuky'||c==='-'||c==='Mléčné výrobky a vejce')return ['box'];
 return ['sklad'];
}
function occurrencesFor(wh){let cards=stock[wh]||[];let out=[];cards.forEach(card=>{let locs=wh==='PFC Bar'?pfcLocations(card):['bar'];locs.forEach((loc,j)=>out.push({...card,occId:card.id+'@'+loc,location:loc,occOrder:j}))});return out}
function locations(){return warehouse==='PFC Bar'?PFC_LOCS:DECKO_LOCS}function activeLocations(){return locations().filter(x=>x.enabled)}function allOcc(){let enabled=new Set(activeLocations().map(x=>x.id));return occurrencesFor(warehouse).filter(x=>enabled.has(x.location))}
function locOcc(loc){return allOcc().filter(x=>x.location===loc).sort((a,b)=>a.category.localeCompare(b.category,'cs')||a.sourceOrder-b.sourceOrder)}
function value(id){return state[warehouse]?.[id]??''}function setValue(id,v){state[warehouse]??={};if(v===''||v===null||Number.isNaN(v))delete state[warehouse][id];else state[warehouse][id]=Number(v);save()}
function save(){localStorage.setItem(K_STATE,JSON.stringify(state));localStorage.setItem(K_WH,warehouse);localStorage.setItem(K_POS,JSON.stringify(position));localStorage.setItem(K_CUSTOM,JSON.stringify(stock))}
function doneCount(){return allOcc().filter(x=>value(x.occId)!=='').length}function totalCount(){return allOcc().length}function sumCard(cardId){return allOcc().filter(x=>x.id===cardId).reduce((s,x)=>s+(Number(value(x.occId))||0),0)}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden')}
function updateHome(){document.querySelectorAll('[data-wh]').forEach(b=>b.classList.toggle('active',b.dataset.wh===warehouse));let d=doneCount(),t=totalCount();$('doneCount').textContent=d;$('leftCount').textContent=t-d;$('pct').textContent=t?Math.round(d/t*100)+' %':'0 %';$('status').textContent=`${warehouse} · ${stock[warehouse]?.length||0} karet`;$('heroTitle').textContent=`Inventura ${warehouse}`;$('heroText').textContent=warehouse==='PFC Bar'?'Pořadí podle skutečné trasy provozem. Jedna skladová karta se může sečíst z více míst.':'Položky Déčka jsou načtené. Fyzickou mapu míst doplníme po první inventuře.'}
document.querySelectorAll('[data-wh]').forEach(b=>b.onclick=()=>{warehouse=b.dataset.wh;save();updateHome()});
function renderLocations(){let html=locations().map(l=>{let arr=l.enabled?locOcc(l.id):[],d=arr.filter(x=>value(x.occId)!=='').length;return `<button class="locationCard ${l.enabled?'':'disabled'}" data-loc="${l.id}" ${l.enabled?'':'disabled'}><b>${esc(l.name)}</b><span>${l.enabled?d+' / '+arr.length:'zatím vypnuto'}</span><small>${esc(l.desc)}</small>${l.enabled?`<progress max="${arr.length||1}" value="${d}"></progress>`:''}</button>`}).join('');$('locationCards').innerHTML=html;document.querySelectorAll('.locationCard:not([disabled])').forEach(b=>b.onclick=()=>startLocation(b.dataset.loc))}
let currentLoc='',currentIndex=0,currentItems=[];
function startLocation(loc){currentLoc=loc;currentItems=locOcc(loc);currentIndex=position[warehouse]?.[loc]||0;if(currentIndex>=currentItems.length)currentIndex=0;show('quick');renderQuick()}
function current(){return currentItems[currentIndex]}
function guessPackSize(x){let n=norm(x.name),m=n.match(/(\d+[\.,]?\d*)\s*l/);if(m)return Number(m[1].replace(',','.'));if(x.category==='Spirit')return /legendario|matusalem|pampero|republica/.test(n)?.7:1;if(x.category==='Víno')return .75;return 1}
function renderQuick(focus=true){let x=current();if(!x){show('locations');renderLocations();return}let loc=locations().find(l=>l.id===currentLoc);$('locLabel').textContent=loc?.name||currentLoc;$('progressLabel').textContent=`${currentIndex+1} / ${currentItems.length}`;$('progress').max=currentItems.length;$('progress').value=currentItems.filter(y=>value(y.occId)!=='').length;$('place').textContent=loc?.name||currentLoc;$('name').textContent=x.name;$('meta').textContent=`${x.category} · celkem zatím ${format(sumCard(x.id))} ${x.unit}`;$('qty').value=value(x.occId);$('unit').textContent=x.unit;$('calcToggle').classList.toggle('hidden',x.unit!=='l');$('calculator').classList.add('hidden');$('packSize').value=guessPackSize(x);position[warehouse]??={};position[warehouse][currentLoc]=currentIndex;save();if(focus)setTimeout(()=>$('qty').focus(),80)}
function format(n){return Number(n||0).toLocaleString('cs-CZ',{maximumFractionDigits:3})}function setCurrent(v){let x=current();if(!x)return;let s=String(v).replace(',','.');setValue(x.occId,s===''?'':Number(s));updateHome();renderQuick(false)}function move(step){currentIndex=Math.max(0,Math.min(currentItems.length-1,currentIndex+step));renderQuick()}
$('start').onclick=()=>{let first=activeLocations().find(l=>locOcc(l.id).some(x=>value(x.occId)===''))||activeLocations()[0];startLocation(first.id)};$('locationsBtn').onclick=()=>{show('locations');renderLocations()};$('locationsBack').onclick=()=>{show('home');updateHome()};$('backHome').onclick=()=>{show('locations');renderLocations()};$('prev').onclick=()=>move(-1);$('next').onclick=()=>move(1);$('skip').onclick=()=>move(1);$('qty').oninput=e=>setCurrent(e.target.value);$('qty').onkeydown=e=>{if(e.key==='Enter')move(1)};$('plus').onclick=()=>setCurrent(Number(value(current().occId)||0)+1);$('minus').onclick=()=>setCurrent(Math.max(0,Number(value(current().occId)||0)-1));$('clear').onclick=()=>setCurrent('');document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>setCurrent(b.dataset.v));
$('calcToggle').onclick=()=>{$('calculator').classList.toggle('hidden');$('fullCount').focus()};function calc(){let full=Number($('fullCount').value||0),size=Number($('packSize').value||0),ml=Number($('remainderMl').value||0),r=full*size+ml/1000;$('calcResult').textContent=`Výsledek: ${format(r)} l`;return r}$('fullCount').oninput=calc;$('packSize').oninput=calc;$('remainderMl').oninput=calc;$('applyCalc').onclick=()=>setCurrent(calc());
function categories(){return [...new Set((stock[warehouse]||[]).filter(x=>!isKeg(x)&&!isReturnable(x)).map(x=>x.category))].sort((a,b)=>a.localeCompare(b,'cs'))}
function renderList(){let q=norm($('search').value),cat=$('category').value;let cards=(stock[warehouse]||[]).filter(x=>!isKeg(x)&&!isReturnable(x)&&(!cat||x.category===cat)&&(!q||norm(x.name+' '+x.ean).includes(q)));$('rows').innerHTML=cards.map(x=>{let occ=allOcc().filter(o=>o.id===x.id),sum=sumCard(x.id),filled=occ.some(o=>value(o.occId)!=='');let breakdown=occ.map(o=>`${locations().find(l=>l.id===o.location)?.name}: ${value(o.occId)===''?'—':format(value(o.occId))}`).join(' · ');return `<div class="row ${filled?'filled':''}"><div><strong>${esc(x.name)}</strong><small>${esc(x.category)}</small></div><input inputmode="decimal" value="${filled?format(sum):''}" data-card="${x.id}"><span>${esc(x.unit)}</span><div class="breakdown">${esc(breakdown)}</div></div>`}).join('');document.querySelectorAll('.row input').forEach(i=>i.onchange=e=>{let card=e.target.dataset.card,occ=allOcc().filter(o=>o.id===card);occ.forEach(o=>setValue(o.occId,''));if(e.target.value!=='')setValue(occ[0].occId,Number(e.target.value.replace(',','.')));renderList();updateHome()})}
$('listBtn').onclick=()=>{show('list');$('category').innerHTML='<option value="">Všechny kategorie</option>'+categories().map(x=>`<option>${esc(x)}</option>`).join('');renderList()};$('listBack').onclick=()=>{show('home');updateHome()};$('search').oninput=renderList;$('category').onchange=renderList;
$('menu').onclick=()=>$('drawer').showModal();$('close').onclick=()=>$('drawer').close();function download(n,c,t){let a=document.createElement('a'),u=URL.createObjectURL(new Blob([c],{type:t}));a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
$('export').onclick=()=>{let cards=(stock[warehouse]||[]).filter(x=>!isKeg(x)&&!isReturnable(x));let rows=[['Název','Kategorie','Jednotka','Skutečný stav'],...cards.map(x=>[x.name,x.category,x.unit,sumCard(x.id)])];let csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\r\n');download(`Inventura_${warehouse.replace(' ','_')}_${new Date().toISOString().slice(0,10)}.csv`,csv,'text/csv;charset=utf-8');$('drawer').close()};$('backup').onclick=()=>download('Inventury_zaloha.json',JSON.stringify({stock,state,warehouse,position},null,2),'application/json');$('reset').onclick=()=>{if(confirm(`Opravdu vymazat inventuru skladu ${warehouse}?`)){state[warehouse]={};position[warehouse]={};save();updateHome();$('drawer').close()}};
function parseLine(line,d){let r=[],c='',q=false;for(let i=0;i<line.length;i++){let ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){c+='"';i++}else q=!q}else if(ch===d&&!q){r.push(c);c=''}else c+=ch}r.push(c);return r}
$('csv').onchange=async e=>{let file=e.target.files[0];if(!file)return;let text=await file.text(),lines=text.split(/\r?\n/).filter(Boolean),d=lines[0].includes(';')?';':',',h=parseLine(lines[0],d).map(norm),ix=n=>h.indexOf(norm(n));if(ix('Název')<0||ix('Jednotka')<0){alert('Export neobsahuje sloupce Název a Jednotka.');return}let wh=prompt('Pro který sklad je export? Napiš PFC nebo Déčko.',warehouse);if(!wh)return;wh=norm(wh).includes('deck')?'Déčko':'PFC Bar';stock[wh]=lines.slice(1).map((l,i)=>{let c=parseLine(l,d),g=n=>ix(n)>=0?(c[ix(n)]||'').trim():'';let name=g('Název');return{id:`${norm(wh)}-${i}-${norm(name).replace(/[^a-z0-9]/g,'')}`,name,ean:g('EAN'),category:g('Kategorie')||'Bez kategorie',unit:g('Jednotka'),warehouse:wh,sourceOrder:i+1}}).filter(x=>x.name);state[wh]={};position[wh]={};warehouse=wh;save();updateHome();alert(`Načteno ${stock[wh].length} skladových karet do ${wh}.`);e.target.value=''};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');updateHome();
