const K_ITEMS="pfc_items_v02",K_VALUES="pfc_values_v02",K_INDEX="pfc_index_v02";
let items=JSON.parse(localStorage.getItem(K_ITEMS)||"null")||window.DEFAULT_CARDS;let values=JSON.parse(localStorage.getItem(K_VALUES)||"{}");let index=Number(localStorage.getItem(K_INDEX)||0);
const $=id=>document.getElementById(id);const save=()=>{localStorage.setItem(K_ITEMS,JSON.stringify(items));localStorage.setItem(K_VALUES,JSON.stringify(values));localStorage.setItem(K_INDEX,index)};
function norm(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden')}
function done(){return items.filter(x=>values[x.id]!==undefined&&values[x.id]!=="").length}function updateSummary(){let d=done();$('doneCount').textContent=d;$('leftCount').textContent=items.length-d;$('pct').textContent=Math.round(d/items.length*100)+' %';$('status').textContent=`PFC Bar · ${items.length} položek`}
function current(){if(index<0)index=0;if(index>=items.length)index=items.length-1;return items[index]}
function renderQuick(focus=true){let x=current(),v=values[x.id]??'';$('progressLabel').textContent=`${index+1} / ${items.length}`;$('progress').max=items.length;$('progress').value=done();$('place').textContent=x.location;$('name').textContent=x.name;$('meta').textContent=`${x.category}${x.ean?' · EAN '+x.ean:''}`;$('qty').value=v;$('unit').textContent=x.unit;save();if(focus)setTimeout(()=>$('qty').focus(),80)}
function setVal(v){let x=current();if(v===''||v===null)delete values[x.id];else values[x.id]=Number(String(v).replace(',','.'));save();updateSummary();renderQuick(false)}
function move(step){index=Math.max(0,Math.min(items.length-1,index+step));renderQuick()}
$('start').onclick=()=>{show('quick');renderQuick()};$('backHome').onclick=()=>{show('home');updateSummary()};$('prev').onclick=()=>move(-1);$('next').onclick=()=>move(1);$('skip').onclick=()=>move(1);$('qty').oninput=e=>setVal(e.target.value);$('qty').onkeydown=e=>{if(e.key==='Enter')move(1)};$('plus').onclick=()=>setVal(Number(values[current().id]||0)+1);$('minus').onclick=()=>setVal(Math.max(0,Number(values[current().id]||0)-1));$('clear').onclick=()=>setVal('');document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>setVal(b.dataset.v));
function categories(){return [...new Set(items.map(x=>x.category))]}function renderList(){let q=norm($('search').value),cat=$('category').value;let list=items.filter(x=>(!cat||x.category===cat)&&(!q||norm(x.name+' '+x.ean).includes(q)));$('rows').innerHTML=list.map(x=>`<div class="row ${values[x.id]!==undefined?'filled':''}"><div><strong>${esc(x.name)}</strong><small>${esc(x.category)}</small></div><input inputmode="decimal" value="${esc(values[x.id]??'')}" data-id="${x.id}"><span>${esc(x.unit)}</span></div>`).join('');document.querySelectorAll('.row input').forEach(i=>i.oninput=e=>{let id=e.target.dataset.id;if(e.target.value==='')delete values[id];else values[id]=Number(e.target.value.replace(',','.'));e.target.closest('.row').classList.toggle('filled',e.target.value!=='');save();updateSummary()})}
$('listBtn').onclick=()=>{show('list');$('category').innerHTML='<option value="">Všechny kategorie</option>'+categories().map(x=>`<option>${esc(x)}</option>`).join('');renderList()};$('listBack').onclick=()=>{show('home');updateSummary()};$('search').oninput=renderList;$('category').onchange=renderList;
$('menu').onclick=()=>$('drawer').showModal();$('close').onclick=()=>$('drawer').close();function download(n,c,t){let a=document.createElement('a'),u=URL.createObjectURL(new Blob([c],{type:t}));a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
$('export').onclick=()=>{let rows=[['Název','Kategorie','Jednotka','Skutečný stav'],...items.map(x=>[x.name,x.category,x.unit,values[x.id]??''])];let csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\r\n');download('Inventura_PFC_'+new Date().toISOString().slice(0,10)+'.csv',csv,'text/csv;charset=utf-8');$('drawer').close()};$('backup').onclick=()=>download('Inventura_PFC_zaloha.json',JSON.stringify({items,values,index},null,2),'application/json');$('reset').onclick=()=>{if(confirm('Opravdu vymazat všechny zadané hodnoty?')){values={};index=0;save();updateSummary();$('drawer').close()}};
function parseLine(line,d){let r=[],c='',q=false;for(let i=0;i<line.length;i++){let ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){c+='"';i++}else q=!q}else if(ch===d&&!q){r.push(c);c=''}else c+=ch}r.push(c);return r}
$('csv').onchange=async e=>{let text=await e.target.files[0].text(),lines=text.split(/\r?\n/).filter(Boolean),d=lines[0].includes(';')?';':',',h=parseLine(lines[0],d).map(norm);let ix=n=>h.indexOf(norm(n));if(ix('Název')<0||ix('Jednotka')<0){alert('Export neobsahuje sloupce Název a Jednotka.');return}items=lines.slice(1).map((l,i)=>{let c=parseLine(l,d),g=n=>ix(n)>=0?(c[ix(n)]||'').trim():'';let name=g('Název');return{id:'csv-'+i+'-'+norm(name).replace(/[^a-z0-9]/g,''),name,ean:g('EAN'),category:g('Kategorie')||'Bez kategorie',unit:g('Jednotka'),warehouse:'PFC Bar',location:g('Kategorie')||'Bez kategorie',order:i+1}}).filter(x=>x.name);values={};index=0;save();updateSummary();alert(`Načteno ${items.length} skladových karet.`);e.target.value=''};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');updateSummary();