const VERSION='v05';
const K_STATE='inventory_state_'+VERSION,K_WH='inventory_warehouse_'+VERSION,K_POS='inventory_position_'+VERSION,K_CUSTOM='inventory_custom_'+VERSION,K_PACK='inventory_packages_'+VERSION;
const $=id=>document.getElementById(id), norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim(), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let stock=JSON.parse(localStorage.getItem(K_CUSTOM)||'null')||window.STOCK_DATA;
let state=JSON.parse(localStorage.getItem(K_STATE)||'{}'),warehouse=localStorage.getItem(K_WH)||'PFC Bar',position=JSON.parse(localStorage.getItem(K_POS)||'{}');
let packs=JSON.parse(localStorage.getItem(K_PACK)||'{}');
const PFC_LOCS=[{id:'sklep',name:'Jeskyně / sklep',desc:'Plné a načaté sudy s pivem',enabled:true},{id:'sklad',name:'Sklad',desc:'Basy s pivem a nealkem',enabled:true},{id:'regal',name:'Regál',desc:'Tvrdý alkohol a víno',enabled:true},{id:'lednice',name:'Nealko lednice',desc:'Chlazené nealko, pivo a načaté víno',enabled:true},{id:'vinoteka',name:'Vinotéka',desc:'Lahvová vína',enabled:true},{id:'box',name:'Chladicí box',desc:'Bedny prosecca, nealko vína, PET a občas pivo',enabled:true}];
const DECKO_LOCS=[{id:'bar',name:'Bar / sklad Déčko',desc:'Dočasné pořadí podle kategorií',enabled:true}];
function save(){localStorage.setItem(K_STATE,JSON.stringify(state));localStorage.setItem(K_WH,warehouse);localStorage.setItem(K_POS,JSON.stringify(position));localStorage.setItem(K_CUSTOM,JSON.stringify(stock));localStorage.setItem(K_PACK,JSON.stringify(packs))}
function isKeg(x){return /\bkeg\b|sud/i.test(x.name)}
function isWeightKeg(x){return isKeg(x)&&x.unit==='l'}
function isSpiritWeight(x){return x.category==='Spirit'&&x.unit==='l'}
function isReturnable(x){return x.category==='Obaly'||/vratn|kelimek|pet lahev 2/i.test(norm(x.name))}
function pfcLocations(x){if(isKeg(x))return ['sklep'];if(isReturnable(x))return [];const n=norm(x.name),c=x.category;if(c==='Spirit')return ['regal'];if(c==='Víno'){if(/prosecco|nealko|sparkling|dc /.test(n))return ['regal','lednice','vinoteka','box'];if(/fangalo|bib/.test(n))return ['regal','lednice'];return ['regal','lednice','vinoteka']}if(c==='Pivo'||c==='Pivo Permon')return ['sklad','lednice','box'];if(c==='Nealko'){if(/sirup|bib/.test(n))return ['sklad'];if(/pet|kofola|coca|sprite|voda/.test(n))return ['sklad','lednice','box'];return ['sklad','lednice']}if(c==='Káva'||c==='Koloniál')return ['sklad'];if(c==='Nanuky'||c==='-'||c==='Mléčné výrobky a vejce')return ['box'];return ['sklad']}
function occurrencesFor(wh){let out=[];(stock[wh]||[]).forEach(card=>(wh==='PFC Bar'?pfcLocations(card):['bar']).forEach((loc,j)=>out.push({...card,occId:card.id+'@'+loc,location:loc,occOrder:j})));return out}
function locations(){return warehouse==='PFC Bar'?PFC_LOCS:DECKO_LOCS}function activeLocations(){return locations().filter(x=>x.enabled)}function allOcc(){let enabled=new Set(activeLocations().map(x=>x.id));return occurrencesFor(warehouse).filter(x=>enabled.has(x.location))}function locOcc(loc){return allOcc().filter(x=>x.location===loc).sort((a,b)=>a.category.localeCompare(b.category,'cs')||a.sourceOrder-b.sourceOrder)}
function value(id){return state[warehouse]?.[id]??''}function setValue(id,v){state[warehouse]??={};if(v===''||v===null||Number.isNaN(v))delete state[warehouse][id];else state[warehouse][id]=Number(v);save()}function sumCard(id){return allOcc().filter(x=>x.id===id).reduce((s,x)=>s+(Number(value(x.occId))||0),0)}function format(n){return Number(n||0).toLocaleString('cs-CZ',{maximumFractionDigits:3})}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden')}
function updateHome(){document.querySelectorAll('[data-wh]').forEach(b=>b.classList.toggle('active',b.dataset.wh===warehouse));let d=allOcc().filter(x=>value(x.occId)!=='').length,t=allOcc().length;$('doneCount').textContent=d;$('leftCount').textContent=t-d;$('pct').textContent=t?Math.round(d/t*100)+' %':'0 %';$('status').textContent=`${warehouse} · ${stock[warehouse]?.length||0} karet`;$('heroTitle').textContent=`Inventura ${warehouse}`;$('heroText').textContent=warehouse==='PFC Bar'?'Jeskyně → sklad → regál → nealko lednice → vinotéka → chladicí box. Prázdné sudy a vratné obaly se nepočítají.':'Položky Déčka jsou načtené. Fyzickou mapu míst doplníme později.'}
document.querySelectorAll('[data-wh]').forEach(b=>b.addEventListener('click',()=>{warehouse=b.dataset.wh;save();updateHome()}));
function renderLocations(){$('locationCards').innerHTML=locations().map(l=>{let arr=l.enabled?locOcc(l.id):[],d=arr.filter(x=>value(x.occId)!=='').length;return `<button class="locationCard" data-loc="${l.id}"><b>${esc(l.name)}</b><span>${d} / ${arr.length}</span><small>${esc(l.desc)}</small><progress max="${arr.length||1}" value="${d}"></progress></button>`}).join('');document.querySelectorAll('.locationCard').forEach(b=>b.addEventListener('click',()=>startLocation(b.dataset.loc)))}
let currentLoc='',currentIndex=0,currentItems=[];function current(){return currentItems[currentIndex]}
function startLocation(loc){currentLoc=loc;currentItems=locOcc(loc);currentIndex=position[warehouse]?.[loc]||0;if(currentIndex>=currentItems.length)currentIndex=0;show('quick');renderQuick()}
function packForKeg(size){let key='keg'+size;packs[key]??={label:`KEG ${size} l`,emptyKg:''};return packs[key]}
function bottlePack(x){let key='bottle:'+x.id;packs[key]??={label:x.name,emptyG:'',fullG:'',volumeL:guessBottleVolume(x)};return packs[key]}
function guessBottleVolume(x){let m=norm(x.name).match(/(0[\.,]\d+|1[\.,]?0?)\s*l/);if(m)return Number(m[1].replace(',','.'));if(/legendario|matusalem|pampero|republica|diplom/.test(norm(x.name)))return .7;if(/zufanek|žufanek/.test(norm(x.name)))return .5;return 1}
function kegSizes(x){let n=norm(x.name);if(/pilsner urquell/.test(n))return [50,30,15];if(/radegast/.test(n))return [50];if(/summer ale|p\.a\.p\.a|papa/.test(n))return [30];if(/bpg|proud/.test(n))return [50,30,15];return [50,30,15]}
function renderQuick(focus=true){let x=current();if(!x){show('locations');renderLocations();return}let loc=locations().find(l=>l.id===currentLoc);$('locLabel').textContent=loc?.name||currentLoc;$('progressLabel').textContent=`${currentIndex+1} / ${currentItems.length}`;$('progress').max=currentItems.length;$('progress').value=currentItems.filter(y=>value(y.occId)!=='').length;$('place').textContent=loc?.name||currentLoc;$('name').textContent=x.name;$('meta').textContent=`${x.category} · celkem zatím ${format(sumCard(x.id))} ${x.unit}`;$('qty').value=value(x.occId);$('unit').textContent=x.unit;$('calculator').classList.add('hidden');let special=isWeightKeg(x)||isSpiritWeight(x)||x.unit==='l';$('calcToggle').classList.toggle('hidden',!special);$('calcToggle').textContent=isWeightKeg(x)?'Spočítat sudy a váhu načatého KEGu':isSpiritWeight(x)?'Spočítat plné lahve a váhu načaté':'Přepočítat obaly a zbytek';position[warehouse]??={};position[warehouse][currentLoc]=currentIndex;save();if(focus)setTimeout(()=>$('qty').focus(),60)}
function setCurrent(v){let x=current();if(!x)return;let s=String(v).replace(',','.');setValue(x.occId,s===''?'':Number(s));updateHome();renderQuick(false)}
function nextLocationAfter(loc){let a=activeLocations(),i=a.findIndex(x=>x.id===loc);return i>=0&&i<a.length-1?a[i+1]:null}function finishLocation(){let here=locations().find(l=>l.id===currentLoc),next=nextLocationAfter(currentLoc);$('completeTitle').textContent=`${here?.name||currentLoc} dokončeno`;$('completeText').textContent=next?`Další místo na trase: ${next.name}.`:'Dokončil jsi poslední místo této provozovny.';$('continueNext').classList.toggle('hidden',!next);if(next){$('continueNext').textContent=`Pokračovat: ${next.name}`;$('continueNext').dataset.loc=next.id}show('complete')}function move(step){if(step>0&&currentIndex>=currentItems.length-1){finishLocation();return}currentIndex=Math.max(0,Math.min(currentItems.length-1,currentIndex+step));renderQuick()}
function openCalculator(){let x=current();$('calculator').classList.remove('hidden');if(isWeightKeg(x))renderKegCalculator(x);else if(isSpiritWeight(x))renderSpiritCalculator(x);else renderSimpleCalculator(x)}
function renderKegCalculator(x){let sizes=kegSizes(x),options=sizes.map(s=>`<option value="${s}">${s} l</option>`).join('');$('calculator').innerHTML=`<h3>Plné sudy</h3><div class="kegSizes">${sizes.map(s=>`<label>${s} l<input id="kegCount${s}" type="number" inputmode="numeric" min="0" step="1" placeholder="0"></label>`).join('')}</div><div class="calcSection"><h3>Načatý sud</h3><div class="fieldGrid"><label for="openKegSize">Velikost KEGu</label><select id="openKegSize">${options}</select><span>l</span></div><div class="fieldGrid"><label for="grossKegKg">Zvážená hmotnost</label><input id="grossKegKg" type="number" inputmode="decimal" min="0" step="0.001" placeholder="0"><span>kg</span></div><div id="kegEmptyInfo" class="warning"></div></div><button id="applySpecial" class="primary">Použít výsledek</button><small id="calcResult"></small>`;let recalc=()=>{let total=sizes.reduce((s,z)=>s+(Number($('kegCount'+z).value)||0)*z,0),size=Number($('openKegSize').value),gross=Number($('grossKegKg').value)||0,empty=Number(packForKeg(size).emptyKg)||0;let opened=gross&&empty?Math.max(0,gross-empty):0;total+=opened;$('kegEmptyInfo').textContent=empty?`Prázdný KEG ${size} l: ${format(empty)} kg. Načatý obsah: ${format(opened)} l.`:`Hmotnost prázdného KEGu ${size} l zatím není nastavena. Nastav ji v Obalech.`;$('calcResult').textContent=`Výsledek pro Storyous: ${format(total)} l`;return total};$('openKegSize').addEventListener('change',recalc);$('calculator').querySelectorAll('input').forEach(i=>i.addEventListener('input',recalc));$('applySpecial').addEventListener('click',()=>setCurrent(recalc()));recalc()}
function renderSpiritCalculator(x){let p=bottlePack(x);$('calculator').innerHTML=`<h3>${esc(x.name)}</h3><div class="fieldGrid"><label for="fullBottles">Neotevřené lahve</label><input id="fullBottles" type="number" inputmode="numeric" min="0" step="1" placeholder="0"><span>ks</span></div><div class="fieldGrid"><label for="grossBottleG">Hmotnost načaté lahve</label><input id="grossBottleG" type="number" inputmode="decimal" min="0" step="1" placeholder="0"><span>g</span></div><div id="bottleInfo" class="warning"></div><button id="applySpecial" class="primary">Použít výsledek</button><small id="calcResult"></small>`;let recalc=()=>{let full=Number($('fullBottles').value)||0,gross=Number($('grossBottleG').value)||0,empty=Number(p.emptyG)||0,fullG=Number(p.fullG)||0,vol=Number(p.volumeL)||0;let opened=0;if(gross&&fullG>empty&&vol)opened=Math.max(0,(gross-empty)/(fullG-empty)*vol);let total=full*vol+opened;$('bottleInfo').textContent=(empty&&fullG&&vol)?`Obal: ${format(empty)} g, plná lahev: ${format(fullG)} g, objem: ${format(vol)} l. Načatá lahev: ${format(opened)} l.`:'Chybí hmotnost prázdné nebo plné lahve. Nastav ji v Obalech.';$('calcResult').textContent=`Výsledek pro Storyous: ${format(total)} l`;return total};$('calculator').querySelectorAll('input').forEach(i=>i.addEventListener('input',recalc));$('applySpecial').addEventListener('click',()=>setCurrent(recalc()));recalc()}
function renderSimpleCalculator(x){$('calculator').innerHTML=`<div class="fieldGrid"><label>Počet plných obalů</label><input id="simpleFull" type="number" min="0" step="1"><span>ks</span></div><div class="fieldGrid"><label>Objem obalu</label><input id="simpleSize" type="number" min="0" step="0.01" value="${guessBottleVolume(x)}"><span>l</span></div><div class="fieldGrid"><label>Zbytek</label><input id="simpleRem" type="number" min="0" step="1"><span>ml</span></div><button id="applySpecial" class="primary">Použít výsledek</button><small id="calcResult"></small>`;let recalc=()=>{let r=(Number($('simpleFull').value)||0)*(Number($('simpleSize').value)||0)+(Number($('simpleRem').value)||0)/1000;$('calcResult').textContent=`Výsledek pro Storyous: ${format(r)} l`;return r};$('calculator').querySelectorAll('input').forEach(i=>i.addEventListener('input',recalc));$('applySpecial').addEventListener('click',()=>setCurrent(recalc()));recalc()}
function renderPackages(){let keg=[50,30,15].map(s=>{let p=packForKeg(s);return `<div class="fieldGrid"><label for="emptyKeg${s}">Prázdný KEG ${s} l</label><input id="emptyKeg${s}" data-pack="keg${s}" data-field="emptyKg" type="number" inputmode="decimal" min="0" step="0.001" value="${esc(p.emptyKg)}"><select data-unit-for="emptyKeg${s}"><option value="kg">kg</option><option value="g">g</option></select></div>`}).join('');let spirits=(stock['PFC Bar']||[]).filter(isSpiritWeight).map(x=>{let p=bottlePack(x);return `<div class="packageGroup"><h3>${esc(x.name)}</h3><small>Výstup skladové karty: litry</small><div class="fieldGrid"><label>Objem lahve</label><input data-bottle="${esc(x.id)}" data-field="volumeL" type="number" min="0" step="0.01" value="${esc(p.volumeL)}"><span>l</span></div><div class="fieldGrid"><label>Prázdná lahev</label><input data-bottle="${esc(x.id)}" data-field="emptyG" type="number" min="0" step="1" value="${esc(p.emptyG)}"><span>g</span></div><div class="fieldGrid"><label>Plná neotevřená lahev</label><input data-bottle="${esc(x.id)}" data-field="fullG" type="number" min="0" step="1" value="${esc(p.fullG)}"><span>g</span></div></div>`}).join('');$('packageRows').innerHTML=`<div class="packageGroup"><h3>Sudové obaly</h3><small>Hmotnost můžeš zadat v kg nebo g. Uložení probíhá automaticky.</small>${keg}<div id="packHint" class="saveHint"></div></div><h2>Lahve Spiritu</h2>${spirits||'<p>Žádné položky.</p>'}`;document.querySelectorAll('[data-pack]').forEach(inp=>inp.addEventListener('input',()=>{let unit=document.querySelector(`[data-unit-for="${inp.id}"]`).value,val=Number(inp.value)||'';packs[inp.dataset.pack]??={};packs[inp.dataset.pack][inp.dataset.field]=val===''?'':unit==='g'?val/1000:val;save();$('packHint').textContent='Uloženo';setTimeout(()=>{$('packHint').textContent=''},900)}));document.querySelectorAll('[data-unit-for]').forEach(sel=>sel.addEventListener('change',()=>{let inp=$(sel.dataset.unitFor),p=packs[inp.dataset.pack],kg=Number(p?.emptyKg)||0;inp.value=sel.value==='g'?kg*1000:kg}));document.querySelectorAll('[data-bottle]').forEach(inp=>inp.addEventListener('input',()=>{let p=bottlePack({id:inp.dataset.bottle,name:'',category:'Spirit'});p[inp.dataset.field]=inp.value===''?'':Number(inp.value);save()}))}
function categories(){return [...new Set((stock[warehouse]||[]).filter(x=>!isReturnable(x)).map(x=>x.category))].sort((a,b)=>a.localeCompare(b,'cs'))}
function renderList(){let q=norm($('search').value),cat=$('category').value,cards=(stock[warehouse]||[]).filter(x=>!isReturnable(x)&&(!cat||x.category===cat)&&(!q||norm(x.name+' '+x.ean).includes(q)));$('rows').innerHTML=cards.map(x=>{let occ=allOcc().filter(o=>o.id===x.id),sum=sumCard(x.id),filled=occ.some(o=>value(o.occId)!=='');let breakdown=occ.map(o=>`${locations().find(l=>l.id===o.location)?.name}: ${format(value(o.occId)||0)}`).join(' · ');return `<div class="row ${filled?'filled':''}"><div><strong>${esc(x.name)}</strong><small>${esc(x.category)}</small></div><input data-card="${esc(x.id)}" value="${filled?sum:''}" inputmode="decimal"><b>${esc(x.unit)}</b><div class="breakdown">${esc(breakdown)}</div></div>`}).join('');document.querySelectorAll('[data-card]').forEach(i=>i.addEventListener('change',()=>{let occ=allOcc().filter(o=>o.id===i.dataset.card);if(occ.length){occ.forEach((o,j)=>setValue(o.occId,j===0?(i.value===''?'':Number(String(i.value).replace(',','.'))):''));renderList();updateHome()}}))}
function openList(){show('list');$('category').innerHTML='<option value="">Všechny kategorie</option>'+categories().map(c=>`<option>${esc(c)}</option>`).join('');renderList()}
function download(name,text,type='text/plain'){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function exportCsv(){let rows=[['Název','Kategorie','Množství','Jednotka']];(stock[warehouse]||[]).filter(x=>!isReturnable(x)).forEach(x=>rows.push([x.name,x.category,String(sumCard(x.id)).replace('.',','),x.unit]));download(`inventura-${warehouse}-${new Date().toISOString().slice(0,10)}.csv`,'\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\n'),'text/csv')}
$('start').onclick=()=>{let first=activeLocations().find(l=>locOcc(l.id).some(x=>value(x.occId)===''))||activeLocations()[0];startLocation(first.id)};$('locationsBtn').onclick=()=>{show('locations');renderLocations()};$('packagesBtn').onclick=()=>{show('packages');renderPackages()};$('packagesBack').onclick=()=>{show('home');updateHome()};$('openPackages').onclick=()=>{$('drawer').close();show('packages');renderPackages()};$('locationsBack').onclick=()=>{show('home');updateHome()};$('backHome').onclick=()=>{show('locations');renderLocations()};$('prev').onclick=()=>move(-1);$('next').onclick=()=>move(1);$('skip').onclick=()=>move(1);$('qty').oninput=e=>setCurrent(e.target.value);$('qty').onkeydown=e=>{if(e.key==='Enter')move(1)};$('plus').onclick=()=>setCurrent(Number(value(current().occId)||0)+1);$('minus').onclick=()=>setCurrent(Math.max(0,Number(value(current().occId)||0)-1));$('clear').onclick=()=>setCurrent('');document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>setCurrent(b.dataset.v));$('calcToggle').onclick=openCalculator;$('continueNext').onclick=()=>startLocation($('continueNext').dataset.loc);$('completeLocations').onclick=()=>{show('locations');renderLocations()};$('completeHome').onclick=()=>{show('home');updateHome()};$('listBtn').onclick=openList;$('listBack').onclick=()=>{show('home');updateHome()};$('search').oninput=renderList;$('category').onchange=renderList;$('menu').onclick=()=>$('drawer').showModal();$('close').onclick=()=>$('drawer').close();$('export').onclick=exportCsv;$('backup').onclick=()=>download('inventura-zaloha.json',JSON.stringify({version:VERSION,state,warehouse,position,packs,stock},null,2),'application/json');$('reset').onclick=()=>{if(confirm(`Vymazat rozepsanou inventuru ${warehouse}?`)){state[warehouse]={};position[warehouse]={};save();$('drawer').close();updateHome()}};
$('csv').onchange=async e=>{let f=e.target.files[0];if(!f)return;alert('Aktualizovaný export PFC je už součástí této verze. Obecný import CSV bude doplněn v další úpravě.');e.target.value=''};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');updateHome();show('home');
